import { Geist, Geist_Mono } from "next/font/google";
import '@/app/globals.css'
import PageNav from "@/ui/PageNav";
import Footer from "@/ui/Footer";
import AOSProvider from "@/ui/AOSProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PageNav/>
        <AOSProvider>
          <main> {children}</main>
        </AOSProvider>
        
        <Footer/>
      </body>
    </html>
  );
}
